### PR TITLE
Es6

### PR DESCRIPTION
**Pull request by simonccarter**
Untested! I don't have Spotify api keys. Please test this, especially promises. 

Run locally on node version 6.9.1.

Changes include:
* Use arrow functions
* Use function composition
* Use pure functions
* Replace var with let/const
* Replace initial if/else with just single if
* Move what looks like unnecessary youtube initialisation outside of youtube function to global scope.
* Replace for loop with forEach
* Replace sys with util
* Global ternary statement rather than unnecessary local if/else for cmd string init

### CODE REVIEW

**Comment by simonccarter** [comment]
Fixed merge conflicts.

**Comment by simonccarter** [comment]
Opps. Stupidly commited youtube api key. I've deleted it, so no problem.

**Comment by adhorrig** [comment]
I was about to comment on the API Key :).. I will test this sometime tomorrow but it mostly looks good from reading through.. Also if you can squash the commits into one, that'd be nice also :)

**Comment by simonccarter** [comment]
New PR at #5

**Pull request closed without merging**
